name: Run EC2 Deployment Script

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'main.tf'
  pull_request:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jinja2

    - name: Run EC2 deployment script
      run: python ./generate_tf.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'santosh09'
        git config --global user.email 'santosh09@gmail.com'
        git add main.tf
        git commit -m 'Update main.tf with new EC2 instance configurations'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN  }}

  run-terraform:
    runs-on: ubuntu-latest
    needs: run-script

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform configuration
      run: terraform apply -auto-approve

