name: Run EC2 Deployment Script

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'main.tf'
  pull_request:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install jinja2

    - name: Print ec2data.txt
      run: cat ec2data.txt

    - name: Run EC2 deployment script
      run: python ./generate_tf.py

    - name: Check if Terraform run is required
      id: check_tf_run
      run: |
        if [ -f tf_run_required.flag ]; then
            echo "Terraform run required"
            echo "tf_run=true" >> $GITHUB_ENV
        else
            echo "Terraform run not required"
            echo "tf_run=false" >> $GITHUB_ENV
        fi

    - name: Commit and push changes
      if: env.tf_run == 'true'
      run: |
        git config --global user.name 'santosh09'
        git config --global user.email 'santosh09@gmail.com'
        git add main.tf
        git commit -m 'Update main.tf with new EC2 instance configurations'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.MYGITHUB_TOKEN }}
        
    - name: check main.tf
      run: cat main.tf
    
    - name: Setup Terraform
      if: env.tf_run == 'true'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
    
    - name: Configure AWS credentials
      if: env.tf_run == 'true'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Initialize Terraform
      if: env.tf_run == 'true'
      run: terraform init

    - name: Apply Terraform configuration
      if: env.tf_run == 'true'
      run: terraform apply -auto-approve

